/* ============================================================
   Analytics performed in this file are based on version 1

   1. OVERALL BUSINESS KPIs
   ============================================================ */

-- Total number of orders
SELECT COUNT(*) AS total_orders 
FROM gold.fact_sales; 


-- Total number of customers
SELECT COUNT(*) AS total_customers 
FROM gold.dim_customer; 


-- Total number of products
SELECT COUNT(*) AS total_products 
FROM gold.dim_products; 


-- Total number of sellers
SELECT COUNT(*) AS total_sellers 
FROM gold.dim_seller; 



/* ============================================================
   2. CUSTOMER ANALYSIS
   ============================================================ */

-- Customers with multiple orders
SELECT COUNT(*) AS repeat_customers 
FROM 
( 
    SELECT customer_unique_id 
    FROM gold.fact_sales 
    GROUP BY customer_unique_id 
    HAVING COUNT(*) > 1 
) t; 


-- Number of customers by state
SELECT 
    customer_state, 
    COUNT(*) AS total_customers 
FROM gold.dim_customer 
GROUP BY customer_state 
ORDER BY total_customers DESC; 


-- Top customers by spending
SELECT TOP 10 
    customer_unique_id, 
    COUNT(*) AS total_orders, 
    SUM(total_price) AS total_spent 
FROM gold.fact_sales 
GROUP BY customer_unique_id 
ORDER BY total_spent DESC; 


-- Classify customers based on their number of orders
SELECT 
    CASE 
        WHEN COUNT(*) = 1 THEN 'One-Time Customer' 
        ELSE 'Repeat Customer' 
    END AS customer_type, 
    COUNT(*) AS customers 
FROM gold.fact_sales 
GROUP BY customer_unique_id; 



/* ============================================================
   3. ORDER & SALES ANALYSIS
   ============================================================ */

-- Monthly order trend
SELECT 
    YEAR(order_purchase_timestamp) AS order_year, 
    MONTH(order_purchase_timestamp) AS order_month, 
    COUNT(*) AS total_orders 
FROM gold.fact_sales 
GROUP BY 
    YEAR(order_purchase_timestamp), 
    MONTH(order_purchase_timestamp) 
ORDER BY 
    order_year, 
    order_month; 


-- Average Order Value (AOV)
SELECT 
    ROUND( 
        AVG(total_price), 
        2 
    ) AS average_order_value 
FROM gold.fact_sales; 


-- Distribution of orders by order status
SELECT 
    order_status, 
    COUNT(*) AS total_orders 
FROM gold.fact_sales 
GROUP BY order_status 
ORDER BY total_orders DESC; 


-- Average delivery time in days
SELECT 
    ROUND(
        AVG(
            DATEDIFF(
                DAY, 
                order_purchase_timestamp, 
                order_delivered_customer_date
            )
        ), 
        2
    ) AS avg_delivery_days 
FROM gold.fact_sales 
WHERE order_delivered_customer_date IS NOT NULL; 


-- Average freight value and average order value
SELECT 
    ROUND(AVG(total_freight_value), 2) AS avg_freight, 
    ROUND(AVG(total_price), 2) AS avg_order_value 
FROM gold.fact_sales; 



/* ============================================================
   4. PRODUCT ANALYSIS
   ============================================================ */

-- Number of items sold for each product
SELECT 
    product_id, 
    COUNT(*) AS items_sold 
FROM silver.sales_ord_items 
GROUP BY product_id 
ORDER BY items_sold DESC; 


-- Most popular products with their category names
SELECT 
    p.product_category_name, 
    pc.total_items 
FROM gold.dim_products AS p 
RIGHT JOIN 
( 
    SELECT 
        COUNT(*) AS total_items, 
        product_id 
    FROM silver.sales_ord_items 
    GROUP BY product_id 
) AS pc 
ON p.product_id = pc.product_id 
ORDER BY pc.total_items DESC; 


-- Total revenue generated by each product
SELECT 
    p.product_category_name, 
    pc.total_revenue 
FROM gold.dim_products p 
RIGHT JOIN 
( 
    SELECT 
        product_id, 
        SUM(price) AS total_revenue 
    FROM silver.sales_ord_items 
    GROUP BY product_id 
) pc 
    ON p.product_id = pc.product_id 
ORDER BY pc.total_revenue DESC; 



/* ============================================================
   5. SELLER ANALYSIS
   ============================================================ */

-- Number of items sold and revenue generated by each seller
SELECT 
    seller_id, 
    COUNT(*) AS items_sold,
    SUM(price) AS total_revenue
FROM silver.sales_ord_items 
GROUP BY seller_id 
ORDER BY items_sold DESC; 



/* ============================================================
   6. PAYMENT ANALYSIS
   ============================================================ */

-- Most frequently used payment methods
SELECT 
    payment_type, 
    COUNT(*) AS payment_count 
FROM silver.finance_ord_payments 
GROUP BY payment_type 
ORDER BY payment_count DESC; 



/* ============================================================
   7. REVIEW ANALYSIS
   ============================================================ */

-- Average customer review score
SELECT 
    ROUND(AVG(review_score), 2) AS average_review_score 
FROM gold.fact_sales;
